achievementData = {
	cardPath = "images/system/banner",
	iconPath = "images/system/icon",
	keyedAchievements = {"runs10", "runs25", "runs50", "runs100", "points10000", "points50000", "points100000", "points500000", "lifetime100000", "lifetime500000", "lifetime1000000", "lifetime10000000", "moon", "moons5", "moons10", "moons25", "daily", "flag", "flags25", "flags50", "flags100", "ufo"},
	achievements = {
		{
			id = "runs10",
			name = "Jumpstart",
			description = "Start 10 runs",
			isSecret = false,
			progressMax = 10,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "runs25",
			name = "Astro Addicted",
			description = "Start 25 runs",
			isSecret = false,
			progressMax = 25,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "runs50",
			name = "Astronaut-in-Chief",
			description = "Start 50 runs",
			isSecret = false,
			progressMax = 50,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "runs100",
			name = "Luna-tic",
			description = "Start 100 runs",
			isSecret = false,
			progressMax = 100,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "points10000",
			name = "Trick Taker",
			description = "Score 10,000 points in a run",
			isSecret = false,
			progressMax = 10000,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "points50000",
			name = "Seasoned Skater",
			description = "Score 50,000 points in a run",
			isSecret = false,
			progressMax = 50000,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "points100000",
			name = "Escape Velocity",
			description = "Score 100,000 points in a run",
			isSecret = false,
			progressMax = 100000,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "points500000",
			name = "Burning Up",
			description = "Score 500,000 points in a run",
			isSecret = false,
			progressMax = 500000,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "lifetime100000",
			name = "Racking Up Scores",
			description = "Score 100,000 lifetime points",
			isSecret = false,
			progressMax = 100000,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "lifetime500000",
			name = "Too Fine a Point",
			description = "Score 500,000 lifetime points",
			isSecret = false,
			progressMax = 500000,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "lifetime1000000",
			name = "Moonman Madman",
			description = "Score 1,000,000 lifetime points",
			isSecret = false,
			progressMax = 1000000,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "lifetime10000000",
			name = "Quote Unquote Life",
			description = "Score 10,000,000 lifetime points",
			isSecret = false,
			progressMax = 10000000,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "moon",
			name = "New Moon",
			description = "Escape to a new moon",
			isSecret = false,
			scoreValue = 1,
		},
		{
			id = "moons5",
			name = "Lunar Cycle",
			description = "See 5 moons in a run",
			isSecret = false,
			progressMax = 5,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "moons10",
			name = "Ebb and Flow",
			description = "See 10 moons in a run",
			isSecret = false,
			progressMax = 10,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "moons25",
			name = "Mortar and Pestle",
			description = "See 25 moons in a run",
			isSecret = false,
			progressMax = 25,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "daily",
			name = "Daily Orbit",
			description = "Play a Daily Orbit",
			isSecret = false,
			scoreValue = 1,
		},
		{
			id = "flag",
			name = "One small step for man...",
			description = "Capture a flag",
			isSecret = true,
			scoreValue = 0,
		},
		{
			id = "flags25",
			name = "...one giant leap for mankind.",
			description = "Capture 25 flags",
			isSecret = true,
			progressMax = 25,
			progressIsPercentage = true,
			scoreValue = 0,
		},
		{
			id = "flags50",
			name = "One small flag in the ground...",
			description = "Capture 50 flags",
			isSecret = true,
			progressMax = 50,
			progressIsPercentage = true,
			scoreValue = 0,
		},
		{
			id = "flags100",
			name = "...one more for the giant collection.",
			description = "Capture 100 flags",
			isSecret = true,
			progressMax = 100,
			progressIsPercentage = true,
			scoreValue = 0,
		},
		{
			id = "ufo",
			name = "Duuude.",
			description = "Spot a UFO",
			isSecret = true,
			scoreValue = 0,
		},
	}
}